Sprint02 us10 tarifs
WildCodeSchool/orleans-0219-php-planet-mini-basket pull request #15
Opened 2019-04-17 09:47 UTC by Jbotany

Pull request pages tarifs

2019-04-17 12:01 UTC, Hyemi-w commented
L.19 prices.twig.html, indentation tr par rapport à body
L.14 prices.twig.html class "tarifsTHead" non présente dans le css ?
L.74 css class "banner-text" présente deux fois sûrement dû à un merge ?
L.54 css class non fermée, sûrement dû à un merge aussi

2019-04-17 13:11 UTC, sblondeau requested changes

2019-04-17 13:11 UTC, sblondeau commented on src/Controller/PricesController.php
> +    public function prices()
index() plutot que prices ()
les noms de méthodes sont généralement des verbes d'action

2019-04-17 13:11 UTC, sblondeau commented on src/Controller/PricesController.php
> +    public function show(int $id)
non! soit tu gères un affichage de tous les prix, soit d'un seul, mais pas les 2 dans une meme PR ! ce sont 2 US différentes.
là ta US touche à l'affichage DES prix, donc le show() est en trop et est à virer

2019-04-17 13:11 UTC, sblondeau commented on src/View/layout.html.twig
>      <link rel="stylesheet" href="https://bootswatch.com/4/sketchy/bootstrap.min.css" crossorigin="anonymous">
meme retour qu'à Jafar, il y a 2 fois bootstrap.min.css de chargé!

2019-04-17 13:29 UTC, Jbotany commented on src/Controller/PricesController.php
> +    public function prices()
corrigé

2019-04-17 13:29 UTC, Jbotany commented on src/Controller/PricesController.php
> +    public function show(int $id)
corrigé

2019-04-17 13:31 UTC, Jbotany commented on src/View/layout.html.twig
>      <link rel="stylesheet" href="https://bootswatch.com/4/sketchy/bootstrap.min.css" crossorigin="anonymous">
C'est normal, nous chargeons Bootstrap puis Bootswatch avec du style sketchy.

2019-04-17 16:06 UTC, sblondeau requested changes

2019-04-17 16:06 UTC, sblondeau commented on src/Controller/PricesController.php
> +class PricesController extends AbstractController
PriceController (tjs au singulier)

2019-04-17 16:06 UTC, sblondeau commented on src/Model/PricesManager.php
> +    const TABLE = 'sport_camp';
normal que le manager s'appelle Price et la table sport_camp ou c'est une erreur ?

2019-04-17 16:06 UTC, sblondeau commented on src/Model/PricesManager.php
> +class PricesManager extends AbstractManager
PriceManager

2019-04-23 10:01 UTC, Jbotany commented on src/Controller/PricesController.php
> +class PricesController extends AbstractController
corrigé

2019-04-23 10:02 UTC, Jbotany commented on src/Model/PricesManager.php
> +class PricesManager extends AbstractManager
corrigé

2019-04-23 10:02 UTC, Jbotany commented on src/Model/PricesManager.php
> +    const TABLE = 'sport_camp';
C'est normal car le prix est géré par stage du coup on le cherche dans une base de donnée commune.

2019-04-23 12:31 UTC, open-it requested changes

2019-04-23 12:31 UTC, open-it commented on src/Controller/PriceController.php
> +        return $this->twig->render('Price/price.html.twig', ['prices' => $prices]);
la vue devrait se nommer index.html.twig

2019-04-23 12:31 UTC, open-it commented on src/View/Price/price.html.twig
> +{% extends 'layout.html.twig' %}
Vous n'avez pas un layoutFront ? ou un truc du genre ? (je ne me rappel plus du nommage)

2019-04-23 12:51 UTC, Jbotany commented on src/Controller/PriceController.php
> +        return $this->twig->render('Price/price.html.twig', ['prices' => $prices]);
corrigé

2019-04-23 12:54 UTC, Jbotany commented on src/View/Price/price.html.twig
> +{% extends 'layout.html.twig' %}
Pour le moment on ne fait que du front. On créera une version admin quand on s'attaquera aux US admin..

2019-04-24 08:36 UTC, open-it approved these changes

2019-04-24 08:37 UTC, merged