Sprint02 us30 nos stages
WildCodeSchool/orleans-0219-php-planet-mini-basket pull request #17
Opened 2019-04-17 12:09 UTC by Dohs

2019-04-17 12:31 UTC, Hyemi-w commented
commentaires vide dans le stage.css, soit les retirer, soit les remplir ;)
ne pas appeler directement les éléments (h1, h4) dans le stage.css ! ça va créer des conflits avec style.css quand on les mergera
pareil avec la class "btn" qui est une class de bootstrap, qui reviendra souvent dans les pages. au final il nous restera que style.css donc il faudrait avoir des classes plus ou moins uniques, sans id cependant

2019-04-17 15:15 UTC, Hyemi-w commented
il te manque le / dans l'appel du css "assets" au lieu de "/assets"

2019-04-17 20:50 UTC, sblondeau requested changes
les images sont encore un peu grosses, je pense que vous pouvez les réduire un peu

2019-04-17 20:50 UTC, sblondeau commented on src/Controller/StageController.php
> +        $stageCamp = new StageManager();
$stageManager = new StageManager() ça reste plus logique ;-)

2019-04-17 20:50 UTC, sblondeau commented on src/View/Stage/stage.html.twig
> +                            <h4 class="stage col-8 "><i class="fas fa-calendar-alt"></i><span class="space">Date de debut
début (accent)

2019-04-24 08:43 UTC, open-it requested changes

2019-04-24 08:43 UTC, open-it commented on src/Controller/StageController.php
> +        return $this->twig->render('Stage/stage.html.twig', ['stages' => $stages]);
la vue devrait être index (le nom de la methode du controller)

2019-04-24 13:02 UTC, open-it approved these changes

2019-04-24 13:03 UTC, merged