Correction bug fix
WildCodeSchool/orleans-0219-php-planet-mini-basket pull request #20
Opened 2019-04-17 15:00 UTC by maiwenn99

Correction Layout and fix view index

2019-04-17 16:06 UTC, sblondeau approved these changes

2019-04-24 09:28 UTC, open-it requested changes

2019-04-24 09:28 UTC, open-it commented on public/assets/css/style.css
> +///////////*BANNER (Elodie)*/////////////
ca n'est pas comme ca que l'on fait un commentaire en CSS ( /* */ )

2019-04-24 09:28 UTC, open-it commented on public/assets/css/style.css
> +////////////////*END BANNER*///////////////////
pareil

2019-04-24 09:28 UTC, open-it commented on public/assets/css/style.css
> +////////////////*MEILLEURES ACTIVITEES (Maïwenn)*//////////////////
pareil

2019-04-24 09:28 UTC, open-it commented on public/assets/css/style.css
> +///////////////*END MEILLEURES ACTIVITEES*///////////////////
pareil

2019-04-24 09:28 UTC, open-it commented on public/assets/css/style.css
> +//////////////////*CARD INTRO (Elodie)*//////////////////////////
pareil

2019-04-24 09:28 UTC, open-it commented on public/assets/css/style.css
> +/////////////////*END CARD INTRO*////////////////
pareil

2019-04-24 09:28 UTC, open-it commented on public/assets/css/style.css
> +////////////*CAROUSEL (Yacine)*////////////
pareil

2019-04-24 09:28 UTC, open-it commented on public/assets/css/style.css
> +///////////////*END CAROUSEL*////////////////
pareil

2019-04-24 09:28 UTC, open-it commented on src/View/Home/_banner.html.twig
> +
je vais pas refuser pr ca ms franchement, ce fichier est présent pour une ligne vide. Pas très utile.

2019-04-26 08:21 UTC, merged