initial layout
WildCodeSchool/orleans-0219-php-planet-mini-basket pull request #21
Opened 2019-04-24 09:17 UTC by maiwenn99

2019-04-24 09:45 UTC, Jbotany commented
Il faut que le controller et le dossier aient le même nom. Et que ce soit écrit en UpperCamelCase.

2019-04-24 09:46 UTC, Jbotany commented
Il faudrait appeler le fichier layoutAdmin et pas index, car ce n'est pas une vue.

2019-04-26 09:03 UTC, sblondeau requested changes
je ne trouve pas cette US dans l'onglet projet
Si le but est de faire une page pour l'admin, mettez au moins un H1 Page d'administraiton

2019-04-29 08:30 UTC, open-it requested changes

2019-04-29 08:30 UTC, open-it commented on src/Controller/AdminController.php
> +        return $this->twig->render('backOffice/index.html.twig');
Le dossier devrait se nommer comme le controller (Admin)

2019-04-29 08:30 UTC, open-it commented on src/View/backOffice/index.html.twig
> +
pourquoi toutes ces lignes vides ? (en fait même si vous répondez, il faut les retirer)

2019-04-29 09:35 UTC, closed without merging