Sprint03 us21 faq gestion
WildCodeSchool/orleans-0219-php-planet-mini-basket pull request #25
Opened 2019-04-26 08:54 UTC by jaffar45

2019-04-26 09:08 UTC, maiwenn99 commented
On a toujours un composer.json et un composer.lock de versionné

2019-04-29 08:41 UTC, open-it requested changes

2019-04-29 08:41 UTC, open-it commented on src/Controller/FaqController.php
> +        return $this->twig->render('Faq/faq.html.twig', [
le fichier de vue devrait s'appeler index.html.twig

2019-04-29 08:41 UTC, open-it commented on src/Controller/FaqAdminController.php
> +class FaqAdminController extends AbstractController
il ne peux pas y avoir de l'admin et du front dans la meme US, soit c'est en tant qu'utilisateur ou soit c'est en tant qu'administrateur.

2019-04-29 08:41 UTC, open-it commented on src/Controller/FaqController.php
> +class FaqController extends AbstractController
il ne peux pas y avoir de l'admin et du front dans la meme US, soit c'est en tant qu'utilisateur ou soit c'est en tant qu'administrateur.

2019-04-29 13:32 UTC, closed without merging