Sprint01 us03 banniere accueil
WildCodeSchool/orleans-0219-php-planet-mini-basket pull request #3
Opened 2019-04-12 09:44 UTC by Hyemi-w

Bannière crée avec ses fichiers.

2019-04-12 10:05 UTC, open-it requested changes
Le .htaccess ne doit pas etre déplacé ! Il doit être à la racine de public.

2019-04-12 10:05 UTC, open-it commented on src/View/Item/banner.html.twig
> +<div class="jumbotron row justify-content-center banner">
Pourquoi le "morceau de vue" est ranger dans Item ?

2019-04-12 10:05 UTC, open-it commented on src/View/Home/index.html.twig
> +    {% include 'Item/banner.html.twig' %}
Pourquoi l'include est il dans le block content ? La banniere devrait faire partie du layout

2019-04-12 10:47 UTC, Jbotany commented on src/View/Item/banner.html.twig
> +<div class="jumbotron row justify-content-center banner">
Corrigé

2019-04-12 10:47 UTC, Jbotany commented on src/View/Home/index.html.twig
> +    {% include 'Item/banner.html.twig' %}
Corrigé

2019-04-15 12:01 UTC, open-it approved these changes

2019-04-15 12:01 UTC, merged